// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'files': string;
  'playTime': string;
  'playbackButtons': string;
  'progress': string;
  'progressWrap': string;
  'progressbar': string;
  'sel': string;
}
export const cssExports: CssExports;
export default cssExports;
